if(dwr==null)var dwr={};if(dwr.util==null)dwr.util={};if(DWRUtil==null)var DWRUtil=dwr.util;dwr.util._escapeHtml=true;dwr.util.setEscapeHtml=function(a){dwr.util._escapeHtml=a};dwr.util._shouldEscapeHtml=function(a){if(a&&a.escapeHtml!=null)return a.escapeHtml;return dwr.util._escapeHtml};dwr.util.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")};dwr.util.unescapeHtml=function(a){return a.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">")};
dwr.util.replaceXmlCharacters=function(a){a=a.replace("&","+");a=a.replace("<","\u2039");a=a.replace(">","\u203a");a=a.replace("'","\u2018");return a=a.replace('"',"\u201c")};dwr.util.containsXssRiskyCharacters=function(a){return a.indexOf("&")!=-1||a.indexOf("<")!=-1||a.indexOf(">")!=-1||a.indexOf("'")!=-1||a.indexOf('"')!=-1};dwr.util.onReturn=function(a,b){if(!a)a=window.event;a&&a.keyCode&&a.keyCode==13&&b()};
dwr.util.selectRange=function(a,b,c){a=dwr.util._getElementById(a,"selectRange()");if(a!=null){if(a.setSelectionRange)a.setSelectionRange(b,c);else if(a.createTextRange){var d=a.createTextRange();d.moveStart("character",b);d.moveEnd("character",c-a.value.length);d.select()}a.focus()}};
if(document.getElementById)dwr.util.byId=function(){for(var a=[],b=0;b<arguments.length;b++){var c=arguments[b];if(typeof c=="string")c=document.getElementById(c);if(arguments.length==1)return c;a.push(c)}return a};else if(document.all)dwr.util.byId=function(){for(var a=[],b=0;b<arguments.length;b++){var c=arguments[b];if(typeof c=="string")c=document.all[c];if(arguments.length==1)return c;a.push(c)}return a};var $;if(!$)$=dwr.util.byId;
dwr.util.toDescriptiveString=function(a,b,c){function d(g,l,m,j){var p="";try{if(typeof g=="string"){g=g;if(l==0&&g.length>j.shortStringMaxLength)g=g.substring(0,j.shortStringMaxLength-3)+"...";if(j.escapeHtml){for(var r=g.split("\n"),n=0;n<r.length;n++)r[n]=dwr.util.escapeHtml(r[n]);g=r.join("\n")}g=l==0?g.replace(/\n|\r|\t/g,function(s){switch(s){case "\n":return"\\n";case "\r":return"";case "\t":return"\\t"}}):g.replace(/\n|\r|\t/g,function(s){switch(s){case "\n":return j.lineTerminator+e(m+1,
j);case "\r":return"";case "\t":return"\\t"}});p='"'+g+'"'}else if(typeof g=="function")p="function";else if(dwr.util._isArray(g))if(l==0)p=g.length>0?"[...]":"[]";else{var i=[];i.push("[");var o=0;for(n=0;n<g.length;n++)if(n in g){var v=g[n];o>0&&i.push(", ");if(l==1){if(o==j.oneLineMaxItems){i.push("...");break}}else i.push(j.lineTerminator+e(m+1,j));if(n!=o){i.push(n);i.push(":")}i.push(d(v,l-1,m+1,j));o++}l>1&&i.push(j.lineTerminator+e(m,j));i.push("]");p=i.join("")}else if(dwr.util._isObject(g)&&
!dwr.util._isDate(g))if(l==0)p=dwr.util._detailedTypeOf(g);else{i=[];if(dwr.util._detailedTypeOf(g)!="Object"){i.push(dwr.util._detailedTypeOf(g));if(typeof g.valueOf()!="object"){i.push(":");i.push(d(g.valueOf(),1,m,j))}i.push(" ")}i.push("{");var w=dwr.util._isHTMLElement(g);o=0;for(var q in g){var t=g[q];if(w){if(!t)continue;if(typeof t=="function")continue;if(k[q])continue;if(q.toUpperCase()==q)continue}o>0&&i.push(", ");if(l==1){if(o==j.oneLineMaxItems){i.push("...");break}}else i.push(j.lineTerminator+
e(m+1,j));i.push(q.length>j.propertyNameMaxLength?q.substring(0,j.propertyNameMaxLength-3)+"...":q);i.push(":");i.push(d(t,l-1,m+1,j));o++}l>1&&o>0&&i.push(j.lineTerminator+e(m,j));i.push("}");p=i.join("")}else p=""+g;return p}catch(u){return u.message?u.message:""+u}}function e(g,l){var m=[];m.push(l.baseIndent);for(var j=0;j<g;j++)m.push(l.childIndent);return m.join("")}if(b===undefined)b=1;var f={};if(dwr.util._isObject(c))f=c;c={escapeHtml:false,baseIndent:"",childIndent:"\u00a0\u00a0",lineTerminator:"\n",
oneLineMaxItems:5,shortStringMaxLength:13,propertyNameMaxLength:30};for(var h in c)h in f||(f[h]=c[h]);var k={document:true,ownerDocument:true,all:true,parentElement:true,parentNode:true,offsetParent:true,children:true,firstChild:true,lastChild:true,previousSibling:true,nextSibling:true,innerHTML:true,outerHTML:true,innerText:true,outerText:true,textContent:true,attributes:true,style:true,currentStyle:true,runtimeStyle:true,parentTextEdit:true};return d(a,b,0,f)};
dwr.util.useLoadingMessage=function(a){var b;b=a?a:"Loading";dwr.engine.setPreHook(function(){var c=dwr.util.byId("disabledZone");if(c){dwr.util.byId("messageZone").innerHTML=b;c.style.visibility="visible";dwr.util._disabledZoneUseCount++}else{c=document.createElement("div");c.setAttribute("id","disabledZone");c.style.position="absolute";c.style.zIndex="1000";c.style.left="0px";c.style.top="0px";c.style.width="100%";c.style.height="100%";document.body.appendChild(c);var d=document.createElement("div");
d.setAttribute("id","messageZone");d.style.position="absolute";d.style.top="0px";d.style.right="0px";d.style.background="red";d.style.color="white";d.style.fontFamily="Arial,Helvetica,sans-serif";d.style.padding="4px";c.appendChild(d);c=document.createTextNode(b);d.appendChild(c);dwr.util._disabledZoneUseCount=1}});dwr.engine.setPostHook(function(){dwr.util._disabledZoneUseCount--;if(dwr.util._disabledZoneUseCount==0)dwr.util.byId("disabledZone").style.visibility="hidden"})};
dwr.util.setHighlightHandler=function(a){dwr.util._highlightHandler=a};dwr.util.yellowFadeHighlightHandler=function(a){dwr.util._yellowFadeProcess(a,0)};dwr.util._yellowFadeSteps=["d0","b0","a0","90","98","a0","a8","b0","b8","c0","c8","d0","d8","e0","e8","f0","f8"];
dwr.util._yellowFadeProcess=function(a,b){a=dwr.util.byId(a);if(b<dwr.util._yellowFadeSteps.length){a.style.backgroundColor="#ffff"+dwr.util._yellowFadeSteps[b];setTimeout("dwr.util._yellowFadeProcess('"+a.id+"',"+(b+1)+")",200)}else a.style.backgroundColor="transparent"};dwr.util.borderFadeHighlightHandler=function(a){a.style.borderWidth="2px";a.style.borderStyle="solid";dwr.util._borderFadeProcess(a,0)};
dwr.util._borderFadeSteps=["d0","b0","a0","90","98","a0","a8","b0","b8","c0","c8","d0","d8","e0","e8","f0","f8"];dwr.util._borderFadeProcess=function(a,b){a=dwr.util.byId(a);if(b<dwr.util._borderFadeSteps.length){a.style.borderColor="#ff"+dwr.util._borderFadeSteps[b]+dwr.util._borderFadeSteps[b];setTimeout("dwr.util._borderFadeProcess('"+a.id+"',"+(b+1)+")",200)}else a.style.backgroundColor="transparent"};dwr.util.focusHighlightHandler=function(a){try{a.focus()}catch(b){}};
dwr.util._highlightHandler=null;dwr.util.highlight=function(a,b){if(b&&b.highlightHandler)b.highlightHandler(dwr.util.byId(a));else dwr.util._highlightHandler!=null&&dwr.util._highlightHandler(dwr.util.byId(a))};
dwr.util.setValue=function(a,b,c){if(b==null)b="";if(c==null)c={};var d=a;if(typeof a=="string")if((a=dwr.util.byId(a))&&a.id!=d)a=null;var e=null;if(a==null){e=document.getElementsByName(d);if(e.length>=1)a=e.item(0)}if(a==null)dwr.util._debug("setValue() can't find an element with id/name: "+d+".");else{dwr.util.highlight(a,c);if(dwr.util._isHTMLElement(a,"select"))a.type=="select-multiple"&&dwr.util._isArray(b)?dwr.util._selectListItems(a,b):dwr.util._selectListItem(a,b);else if(dwr.util._isHTMLElement(a,
"input"))if(a.type=="radio"||a.type=="checkbox")if(e&&e.length>=1)for(c=0;c<e.length;c++){d=e.item(c);if(d.type==a.type)if(dwr.util._isArray(b)){d.checked=false;for(var f=0;f<b.length;f++)if(b[f]==d.value)d.checked=true}else d.checked=d.value==b}else a.checked=b==true;else a.value=b;else if(dwr.util._isHTMLElement(a,"textarea"))a.value=b;else if(b.nodeType){if(b.nodeType==9)b=b.documentElement;b=dwr.util._importNode(a.ownerDocument,b,true);a.appendChild(b)}else if(dwr.util._shouldEscapeHtml(c)&&typeof b==
"string")if(a.textContent)a.textContent=b;else if(a.innerText)a.innerText=b;else a.innerHTML=dwr.util.escapeHtml(b);else a.innerHTML=b}};dwr.util._selectListItems=function(a,b){var c,d;for(c=0;c<a.options.length;c++){a.options[c].selected=false;for(d=0;d<b.length;d++)if(a.options[c].value==b[d])a.options[c].selected=true}for(c=0;c<a.options.length;c++)for(d=0;d<b.length;d++)if(a.options[c].text==b[d])a.options[c].selected=true};
dwr.util._selectListItem=function(a,b){var c=false,d;for(d=0;d<a.options.length;d++)if(a.options[d].value==b)c=a.options[d].selected=true;else a.options[d].selected=false;if(!c)for(d=0;d<a.options.length;d++)a.options[d].selected=a.options[d].text==b};
dwr.util.getValue=function(a,b){if(b==null)b={};var c=a;if(typeof a=="string")if((a=dwr.util.byId(a))&&a.id!=c)a=null;var d=null;if(a==null){d=document.getElementsByName(c);if(d.length>=1)a=d.item(0)}if(a==null){dwr.util._debug("getValue() can't find an element with id/name: "+c+".");return""}if(dwr.util._isHTMLElement(a,"select"))if(a.type=="select-multiple"){b=[];for(c=0;c<a.options.length;c++){d=a.options[c];if(d.selected){var e=d.getAttributeNode("value");e&&e.specified?b.push(d.value):b.push(d.text)}}return b}else{d=
a.selectedIndex;if(d!=-1){d=a.options[d];if((e=d.getAttributeNode("value"))&&e.specified)return d.value;return d.text}else return""}if(dwr.util._isHTMLElement(a,"input")){if(a.type=="radio"){if(d&&d.length>=1)for(c=0;c<d.length;c++){e=d.item(c);if(e.type==a.type)if(e.checked)return e.value}return a.checked}if(a.type=="checkbox"){if(d&&d.length>=1){b=[];for(c=0;c<d.length;c++){e=d.item(c);e.type==a.type&&e.checked&&b.push(e.value)}return b}return a.checked}return a.value}if(dwr.util._isHTMLElement(a,
"textarea"))return a.value;if(dwr.util._shouldEscapeHtml(b))if(a.textContent)return a.textContent;else if(a.innerText)return a.innerText;return a.innerHTML};dwr.util.getText=function(a){a=dwr.util._getElementById(a,"getText()");if(a==null)return null;if(!dwr.util._isHTMLElement(a,"select")){dwr.util._debug("getText() can only be used with select elements. Attempt to use: "+dwr.util._detailedTypeOf(a)+" from  id: "+orig+".");return""}var b=a.selectedIndex;return b!=-1?a.options[b].text:""};
dwr.util.setValues=function(a,b){var c="";if(b&&b.prefix)c=b.prefix;if(b&&b.idPrefix)c=b.idPrefix;dwr.util._setValuesRecursive(a,c)};
dwr.util._setValuesRecursive=function(a,b){if(dwr.util._isArray(a)&&a.length>0&&dwr.util._isObject(a[0]))for(var c=0;c<a.length;c++)dwr.util._setValuesRecursive(a[c],b+"["+c+"]");else if(dwr.util._isObject(a)&&!dwr.util._isArray(a))for(c in a){var d=b?b+"."+c:c;if(dwr.util._isObject(a[c])&&!dwr.util._isArray(a[c])||dwr.util._isArray(a[c])&&a[c].length>0&&dwr.util._isObject(a[c][0]))dwr.util._setValuesRecursive(a[c],d);else if(typeof a[c]!="function")if(dwr.util.byId(d)!=null||document.getElementsByName(d).length>=
1)dwr.util.setValue(d,a[c])}};dwr.util.getValues=function(a,b){if(typeof a=="string"||dwr.util._isHTMLElement(a))return dwr.util.getFormValues(a);else{var c="";if(b!=null&&b.prefix)c=b.prefix;if(b!=null&&b.idPrefix)c=b.idPrefix;dwr.util._getValuesRecursive(a,c);return a}};
dwr.util.getFormValues=function(a){var b=null;if(typeof a=="string"){b=document.forms[a];if(b==null)b=dwr.util.byId(a)}else if(dwr.util._isHTMLElement(a))b=a;if(b!=null){if(b.elements==null){alert("getFormValues() requires an object or reference to a form element.");return null}a={};for(var c,d,e=0;e<b.elements.length;e++)if(!(b[e].type in{button:0,submit:0,reset:0,image:0,file:0})){if(b[e].name){c=b[e].name;d=dwr.util.getValue(c)}else{c=b[e].id?b[e].id:"element"+e;d=dwr.util.getValue(b[e])}a[c]=
d}return a}};
dwr.util._getValuesRecursive=function(a,b){if(dwr.util._isArray(a)&&a.length>0&&dwr.util._isObject(a[0]))for(var c=0;c<a.length;c++)dwr.util._getValuesRecursive(a[c],b+"["+c+"]");else if(dwr.util._isObject(a)&&!dwr.util._isArray(a))for(c in a){var d=b?b+"."+c:c;if(dwr.util._isObject(a[c])&&!dwr.util._isArray(a[c])||dwr.util._isArray(a[c])&&a[c].length>0&&dwr.util._isObject(a[c][0]))dwr.util._getValuesRecursive(a[c],d);else if(typeof a[c]!="function")if(dwr.util.byId(d)!=null||document.getElementsByName(d).length>=1)a[c]=
dwr.util.getValue(d)}};
dwr.util.addOptions=function(a,b){a=dwr.util._getElementById(a,"addOptions()");if(a!=null){var c=dwr.util._isHTMLElement(a,"select"),d=dwr.util._isHTMLElement(a,["ul","ol"]);if(!c&&!d)dwr.util._debug("addOptions() can only be used with select/ul/ol elements. Attempt to use: "+dwr.util._detailedTypeOf(a));else if(b!=null){var e=arguments.length,f={},h=arguments[e-1];if(e>2&&dwr.util._isObject(h)){f=h;e--}h=null;if(e>=3)h=arguments[2];var k=null;if(e>=4)k=arguments[3];if(!f.optionCreator&&c)f.optionCreator=
dwr.util._defaultOptionCreator;if(!f.optionCreator&&d)f.optionCreator=dwr.util._defaultListItemCreator;if(dwr.util._isArray(b))for(var g=0;g<b.length;g++){f.data=b[g];f.text=null;f.value=null;if(c){if(h!=null)if(k!=null){f.text=dwr.util._getValueFrom(b[g],k);f.value=dwr.util._getValueFrom(b[g],h)}else f.text=f.value=dwr.util._getValueFrom(b[g],h);else f.text=f.value=dwr.util._getValueFrom(b[g]);if(f.text!=null||f.value){d=f.optionCreator(f);d.text=f.text;d.value=f.value;a.options[a.options.length]=
d}}else{f.value=dwr.util._getValueFrom(b[g],h);if(f.value!=null){d=f.optionCreator(f);if(dwr.util._shouldEscapeHtml(f))f.value=dwr.util.escapeHtml(f.value);d.innerHTML=f.value;a.appendChild(d)}}}else if(k!=null){if(!c){alert("dwr.util.addOptions can only create select lists from objects.");return}for(g in b){f.data=b[g];f.value=dwr.util._getValueFrom(b[g],h);f.text=dwr.util._getValueFrom(b[g],k);if(f.text!=null||f.value){d=f.optionCreator(f);d.text=f.text;d.value=f.value;a.options[a.options.length]=
d}}}else{if(!c){dwr.util._debug("dwr.util.addOptions can only create select lists from objects.");return}for(g in b)if(typeof b[g]!="function"){f.data=b[g];if(h){f.value=b[g];f.text=g}else{f.value=g;f.text=b[g]}if(f.text!=null||f.value){d=f.optionCreator(f);d.text=f.text;d.value=f.value;a.options[a.options.length]=d}}}dwr.util.highlight(a,f)}}};dwr.util._getValueFrom=function(a,b){return b==null?a:typeof b=="function"?b(a):a[b]};dwr.util._defaultOptionCreator=function(){return new Option};
dwr.util._defaultListItemCreator=function(){return document.createElement("li")};dwr.util.removeAllOptions=function(a){a=dwr.util._getElementById(a,"removeAllOptions()");if(a!=null){var b=dwr.util._isHTMLElement(a,"select"),c=dwr.util._isHTMLElement(a,["ul","ol"]);if(!b&&!c)dwr.util._debug("removeAllOptions() can only be used with select, ol and ul elements. Attempt to use: "+dwr.util._detailedTypeOf(a));else if(b)a.options.length=0;else for(;a.childNodes.length>0;)a.removeChild(a.firstChild)}};
dwr.util.addRows=function(a,b,c,d){a=dwr.util._getElementById(a,"addRows()");if(a!=null)if(dwr.util._isHTMLElement(a,["table","tbody","thead","tfoot"])){d||(d={});if(!d.rowCreator)d.rowCreator=dwr.util._defaultRowCreator;if(!d.cellCreator)d.cellCreator=dwr.util._defaultCellCreator;var e,f;if(dwr.util._isArray(b))for(f=0;f<b.length;f++){d.rowData=b[f];d.rowIndex=f;d.rowNum=f;d.data=null;d.cellNum=-1;e=dwr.util._addRowInner(c,d);e!=null&&a.appendChild(e)}else if(typeof b=="object"){f=0;for(var h in b){d.rowData=
b[h];d.rowIndex=h;d.rowNum=f;d.data=null;d.cellNum=-1;e=dwr.util._addRowInner(c,d);e!=null&&a.appendChild(e);f++}}dwr.util.highlight(a,d)}else dwr.util._debug("addRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(a))};
dwr.util._addRowInner=function(a,b){var c=b.rowCreator(b);if(c==null)return null;for(var d=0;d<a.length;d++){var e=a[d];b.data=typeof e=="function"?e(b.rowData,b):e||"";b.cellNum=d;e=b.cellCreator(b);if(e!=null){if(b.data!=null)if(dwr.util._isHTMLElement(b.data))e.appendChild(b.data);else e.innerHTML=dwr.util._shouldEscapeHtml(b)&&typeof b.data=="string"?dwr.util.escapeHtml(b.data):b.data;c.appendChild(e)}}return c};dwr.util._defaultRowCreator=function(){return document.createElement("tr")};
dwr.util._defaultCellCreator=function(){return document.createElement("td")};dwr.util.removeAllRows=function(a,b){a=dwr.util._getElementById(a,"removeAllRows()");if(a!=null){b||(b={});if(!b.filter)b.filter=function(){return true};if(dwr.util._isHTMLElement(a,["table","tbody","thead","tfoot"]))for(var c=a.firstChild,d;c!=null;){d=c.nextSibling;b.filter(c)&&a.removeChild(c);c=d}else dwr.util._debug("removeAllRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(a))}};
dwr.util.setClassName=function(a,b){a=dwr.util._getElementById(a,"setClassName()");if(a!=null)a.className=b};dwr.util.addClassName=function(a,b){a=dwr.util._getElementById(a,"addClassName()");if(a!=null)a.className+=" "+b};dwr.util.removeClassName=function(a,b){a=dwr.util._getElementById(a,"removeClassName()");if(a!=null)a.className=a.className.replace(new RegExp("(^|\\s)"+b+"(\\s|$)","g"),"")};
dwr.util.toggleClassName=function(a,b){a=dwr.util._getElementById(a,"toggleClassName()");if(a!=null){var c=new RegExp("(^|\\s)"+b+"(\\s|$)");if(c.test(a.className))a.className=a.className.replace(c,"");else a.className+=" "+b}};dwr.util.cloneNode=function(a,b){a=dwr.util._getElementById(a,"cloneNode()");if(a==null)return null;if(b==null)b={};var c=a.cloneNode(true);b.idPrefix||b.idSuffix?dwr.util._updateIds(c,b):dwr.util._removeIds(c);a.parentNode.insertBefore(c,a);return c};
dwr.util._updateIds=function(a,b){if(b==null)b={};if(a.id)a.setAttribute("id",(b.idPrefix||"")+a.id+(b.idSuffix||""));a=a.childNodes;for(var c=0;c<a.length;c++){var d=a.item(c);d.nodeType==1&&dwr.util._updateIds(d,b)}};dwr.util._removeIds=function(a){a.id&&a.removeAttribute("id");a=a.childNodes;for(var b=0;b<a.length;b++){var c=a.item(b);c.nodeType==1&&dwr.util._removeIds(c)}};
dwr.util.cloneNodeForValues=function(a,b,c){a=dwr.util._getElementById(a,"cloneNodeForValues()");if(a==null)return null;if(c==null)c={};return dwr.util._cloneNodeForValuesRecursive(a,b,c.idPrefix!=null?c.idPrefix:a.id||"",c)};
dwr.util._cloneNodeForValuesRecursive=function(a,b,c,d){if(dwr.util._isArray(b)){for(var e=[],f=0;f<b.length;f++){var h=dwr.util._cloneNodeForValuesRecursive(a,b[f],c+"["+f+"]",d);e.push(h)}return e}else if(dwr.util._isObject(b)&&!dwr.util._isArray(b)){h=a.cloneNode(true);if(d.updateCloneStyle&&h.style)for(e in d.updateCloneStyle)h.style[e]=d.updateCloneStyle[e];dwr.util._replaceIds(h,a.id,c);a.parentNode.insertBefore(h,a);dwr.util._cloneSubArrays(b,c,d);return h}return null};
dwr.util._replaceIds=function(a,b,c){if(a.id){var d=null;if(a.id==b)d=c;else if(a.id.length>b.length)if(a.id.substr(0,b.length)==b){var e=a.id.charAt(b.length);if(e=="."||e=="[")d=c+a.id.substr(b.length)}d?a.setAttribute("id",d):a.removeAttribute("id")}a=a.childNodes;for(d=0;d<a.length;d++){e=a.item(d);e.nodeType==1&&dwr.util._replaceIds(e,b,c)}};
dwr.util._cloneSubArrays=function(a,b,c){for(prop in a){var d=a[prop];if(dwr.util._isArray(d)){if(d.length>0&&dwr.util._isObject(d[0])){var e=b+"."+prop,f=dwr.util.byId(e);f!=null&&dwr.util._cloneNodeForValuesRecursive(f,d,e,c)}}else dwr.util._isObject(d)&&dwr.util._cloneSubArrays(d,b+"."+prop,c)}};dwr.util._getElementById=function(a,b){var c=a;a=dwr.util.byId(a);a==null&&dwr.util._debug(b+" can't find an element with id: "+c+".");return a};
dwr.util._isHTMLElement=function(a,b){if(a==null||typeof a!="object"||a.nodeName==null)return false;if(b!=null){a=a.nodeName.toLowerCase();if(typeof b=="string")return a==b.toLowerCase();if(dwr.util._isArray(b)){for(var c=false,d=0;d<b.length&&!c;d++)if(a==b[d].toLowerCase())c=true;return c}dwr.util._debug("dwr.util._isHTMLElement was passed test node name that is neither a string or array of strings");return false}return true};
dwr.util._detailedTypeOf=function(a){var b=typeof a;if(b=="object"){b=Object.prototype.toString.apply(a);b=b.substring(8,b.length-1)}return b};dwr.util._isObject=function(a){return a&&typeof a=="object"};dwr.util._isArray=function(a){return a&&a.join};dwr.util._isDate=function(a){return a&&a.toUTCString?true:false};
dwr.util._importNode=function(a,b,c){var d;if(b.nodeType==1){d=a.createElement(b.nodeName);for(var e=0;e<b.attributes.length;e++){var f=b.attributes[e];f.nodeValue!=null&&f.nodeValue!=""&&d.setAttribute(f.name,f.nodeValue)}if(typeof b.style!="undefined")d.style.cssText=b.style.cssText}else if(b.nodeType==3)d=a.createTextNode(b.nodeValue);if(c&&b.hasChildNodes())for(e=0;e<b.childNodes.length;e++)d.appendChild(dwr.util._importNode(a,b.childNodes[e],true));return d};
dwr.util._debug=function(a,b){var c=false;try{if(window.console){b&&window.console.trace&&window.console.trace();window.console.log(a);c=true}else if(window.opera&&window.opera.postError){window.opera.postError(a);c=true}}catch(d){}if(!c)if(b=document.getElementById("dwr-debug")){a=a+"<br/>"+b.innerHTML;if(a.length>2048)a=a.substring(0,2048);b.innerHTML=a}};if(dwr==null)dwr={};if(dwr.engine==null)dwr.engine={};if(DWREngine==null)var DWREngine=dwr.engine;dwr.engine.setErrorHandler=function(a){dwr.engine._errorHandler=a};dwr.engine.setWarningHandler=function(a){dwr.engine._warningHandler=a};dwr.engine.setTextHtmlHandler=function(a){dwr.engine._textHtmlHandler=a};dwr.engine.setTimeout=function(a){dwr.engine._timeout=a};dwr.engine.setPreHook=function(a){dwr.engine._preHook=a};dwr.engine.setPostHook=function(a){dwr.engine._postHook=a};
dwr.engine.setHeaders=function(a){dwr.engine._headers=a};dwr.engine.setParameters=function(a){dwr.engine._parameters=a};dwr.engine.XMLHttpRequest=1;dwr.engine.IFrame=2;dwr.engine.ScriptTag=3;dwr.engine.setRpcType=function(a){if(a!=dwr.engine.XMLHttpRequest&&a!=dwr.engine.IFrame&&a!=dwr.engine.ScriptTag)dwr.engine._handleError(null,{name:"dwr.engine.invalidRpcType",message:"RpcType must be one of dwr.engine.XMLHttpRequest or dwr.engine.IFrame or dwr.engine.ScriptTag"});else dwr.engine._rpcType=a};
dwr.engine.setHttpMethod=function(a){if(a!="GET"&&a!="POST")dwr.engine._handleError(null,{name:"dwr.engine.invalidHttpMethod",message:"Remoting method must be one of GET or POST"});else dwr.engine._httpMethod=a};dwr.engine.setOrdered=function(a){dwr.engine._ordered=a};dwr.engine.setAsync=function(a){dwr.engine._async=a};
dwr.engine.setActiveReverseAjax=function(a){if(a){if(!dwr.engine._activeReverseAjax){dwr.engine._activeReverseAjax=true;dwr.engine._poll()}}else{dwr.engine._activeReverseAjax&&dwr.engine._pollReq&&dwr.engine._pollReq.abort();dwr.engine._activeReverseAjax=false}};dwr.engine.defaultErrorHandler=function(a,b){dwr.engine._debug("Error: "+b.name+", "+b.message,true);if(a==null||a=="")alert("A server error has occured.");else a.indexOf("0x80040111")!=-1?dwr.engine._debug(a):alert(a)};
dwr.engine.defaultWarningHandler=function(a){dwr.engine._debug(a)};dwr.engine.beginBatch=function(){if(dwr.engine._batch)dwr.engine._handleError(null,{name:"dwr.engine.batchBegun",message:"Batch already begun"});else dwr.engine._batch=dwr.engine._createBatch()};
dwr.engine.endBatch=function(a){var b=dwr.engine._batch;if(b==null)dwr.engine._handleError(null,{name:"dwr.engine.batchNotBegun",message:"No batch in progress"});else{dwr.engine._batch=null;if(b.map.callCount!=0){a&&dwr.engine._mergeBatch(b,a);if(dwr.engine._ordered&&dwr.engine._batchesLength!=0)dwr.engine._batchQueue[dwr.engine._batchQueue.length]=b;else dwr.engine._sendData(b)}}};dwr.engine.setPollMethod=function(a){dwr.engine.setPollType(a)};dwr.engine.setMethod=function(a){dwr.engine.setRpcType(a)};
dwr.engine.setVerb=function(a){dwr.engine.setHttpMethod(a)};dwr.engine.setPollType=function(){dwr.engine._debug("Manually setting the Poll Type is not supported")};dwr.engine._scriptSessionId=null;dwr.engine._getScriptSessionId=function(){if(dwr.engine._scriptSessionId==null)dwr.engine._scriptSessionId=dwr.engine._origScriptSessionId+Math.floor(Math.random()*1E3);return dwr.engine._scriptSessionId};dwr.engine._errorHandler=dwr.engine.defaultErrorHandler;dwr.engine._warningHandler=dwr.engine.defaultWarningHandler;
dwr.engine._preHook=null;dwr.engine._postHook=null;dwr.engine._batches={};dwr.engine._batchesLength=0;dwr.engine._batchQueue=[];dwr.engine._rpcType=dwr.engine.XMLHttpRequest;dwr.engine._httpMethod="POST";dwr.engine._ordered=false;dwr.engine._async=true;dwr.engine._batch=null;dwr.engine._timeout=0;dwr.engine._DOMDocument=["Msxml2.DOMDocument.6.0","Msxml2.DOMDocument.5.0","Msxml2.DOMDocument.4.0","Msxml2.DOMDocument.3.0","MSXML2.DOMDocument","MSXML.DOMDocument","Microsoft.XMLDOM"];
dwr.engine._XMLHTTP=["Msxml2.XMLHTTP.6.0","Msxml2.XMLHTTP.5.0","Msxml2.XMLHTTP.4.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];dwr.engine._activeReverseAjax=false;dwr.engine._outstandingIFrames=[];dwr.engine._pollReq=null;dwr.engine._pollCometInterval=200;dwr.engine._pollRetries=0;dwr.engine._maxPollRetries=0;dwr.engine._textHtmlHandler=null;dwr.engine._headers=null;dwr.engine._parameters=null;dwr.engine._postSeperator="\n";dwr.engine._defaultInterceptor=function(a){return a};
dwr.engine._urlRewriteHandler=dwr.engine._defaultInterceptor;dwr.engine._contentRewriteHandler=dwr.engine._defaultInterceptor;dwr.engine._replyRewriteHandler=dwr.engine._defaultInterceptor;dwr.engine._nextBatchId=0;dwr.engine._propnames=["rpcType","httpMethod","async","timeout","errorHandler","warningHandler","textHtmlHandler"];dwr.engine._partialResponseNo=0;dwr.engine._partialResponseYes=1;dwr.engine._partialResponseFlush=2;dwr.engine._unloading=false;
dwr.engine._execute=function(a,b,c){var d=false;if(dwr.engine._batch==null){dwr.engine.beginBatch();d=true}for(var e=dwr.engine._batch,f=[],h=0;h<arguments.length-3;h++)f[h]=arguments[h+3];if(e.path==null)e.path=a;else if(e.path!=a){dwr.engine._handleError(e,{name:"dwr.engine.multipleServlets",message:"Can't batch requests to multiple DWR Servlets."});return}h=f[f.length-1];h=typeof h=="function"||h==null?{callback:f.pop()}:f.pop();dwr.engine._mergeBatch(e,h);e.handlers[e.map.callCount]={exceptionHandler:h.exceptionHandler,
callback:h.callback};var k="c"+e.map.callCount+"-";e.map[k+"scriptName"]=b;e.map[k+"methodName"]=c;e.map[k+"id"]=e.map.callCount;for(h=0;h<f.length;h++)dwr.engine._serializeAll(e,[],f[h],k+"param"+h);e.map.callCount++;d&&dwr.engine.endBatch()};
dwr.engine._poll=function(){if(dwr.engine._activeReverseAjax){var a=dwr.engine._createBatch();a.map.id=0;a.map.callCount=1;a.isPoll=true;if(dwr.engine._pollWithXhr=="true"){a.rpcType=dwr.engine.XMLHttpRequest;a.map.partialResponse=dwr.engine._partialResponseNo}else if(navigator.userAgent.indexOf("Gecko/")!=-1){a.rpcType=dwr.engine.XMLHttpRequest;a.map.partialResponse=dwr.engine._partialResponseYes}else{a.rpcType=dwr.engine.XMLHttpRequest;a.map.partialResponse=dwr.engine._partialResponseNo}a.httpMethod=
"POST";a.async=true;a.timeout=0;a.path=dwr.engine._defaultPath;a.preHooks=[];a.postHooks=[];a.errorHandler=dwr.engine._pollErrorHandler;a.warningHandler=dwr.engine._pollErrorHandler;a.handlers[0]={callback:function(b){dwr.engine._pollRetries=0;setTimeout(dwr.engine._poll,b)}};dwr.engine._sendData(a);a.rpcType==dwr.engine.XMLHttpRequest&&a.map.partialResponse==dwr.engine._partialResponseYes&&dwr.engine._checkCometPoll()}};
dwr.engine._pollErrorHandler=function(a,b){dwr.engine._pollRetries++;dwr.engine._debug("Reverse Ajax poll failed (pollRetries="+dwr.engine._pollRetries+"): "+b.name+" : "+b.message);if(dwr.engine._pollRetries<dwr.engine._maxPollRetries)setTimeout(dwr.engine._poll,1E4);else{dwr.engine._activeReverseAjax=false;dwr.engine._debug("Giving up.")}};
dwr.engine._createBatch=function(){var a={map:{callCount:0,page:window.location.pathname+window.location.search,httpSessionId:dwr.engine._getJSessionId(),scriptSessionId:dwr.engine._getScriptSessionId()},charsProcessed:0,paramCount:0,parameters:{},headers:{},isPoll:false,handlers:{},preHooks:[],postHooks:[],rpcType:dwr.engine._rpcType,httpMethod:dwr.engine._httpMethod,async:dwr.engine._async,timeout:dwr.engine._timeout,errorHandler:dwr.engine._errorHandler,warningHandler:dwr.engine._warningHandler,
textHtmlHandler:dwr.engine._textHtmlHandler};dwr.engine._preHook&&a.preHooks.push(dwr.engine._preHook);dwr.engine._postHook&&a.postHooks.push(dwr.engine._postHook);var b,c;if(dwr.engine._headers)for(b in dwr.engine._headers){c=dwr.engine._headers[b];if(typeof c!="function")a.headers[b]=c}if(dwr.engine._parameters)for(b in dwr.engine._parameters){c=dwr.engine._parameters[b];if(typeof c!="function")a.parameters[b]=c}return a};
dwr.engine._mergeBatch=function(a,b){var c,d;for(d=0;d<dwr.engine._propnames.length;d++){c=dwr.engine._propnames[d];if(b[c]!=null)a[c]=b[c]}b.preHook!=null&&a.preHooks.unshift(b.preHook);b.postHook!=null&&a.postHooks.push(b.postHook);if(b.headers)for(c in b.headers){d=b.headers[c];if(typeof d!="function")a.headers[c]=d}if(b.parameters)for(c in b.parameters){d=b.parameters[c];if(typeof d!="function")a.map["p-"+c]=""+d}};
dwr.engine._getJSessionId=function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf(dwr.engine._sessionCookieName+"=")==0)return c.substring(dwr.engine._sessionCookieName.length+1,c.length)}return""};
dwr.engine._checkCometPoll=function(){for(var a=0;a<dwr.engine._outstandingIFrames.length;a++){var b="",c=dwr.engine._outstandingIFrames[a];try{b=dwr.engine._getTextFromCometIFrame(c)}catch(d){dwr.engine._handleWarning(c.batch,d)}b!=""&&dwr.engine._processCometResponse(b,c.batch)}if(dwr.engine._pollReq){a=dwr.engine._pollReq;b=a.responseText;b!=null&&dwr.engine._processCometResponse(b,a.batch)}if(dwr.engine._outstandingIFrames.length>0||dwr.engine._pollReq)setTimeout(dwr.engine._checkCometPoll,dwr.engine._pollCometInterval)};
dwr.engine._getTextFromCometIFrame=function(a){a=a.contentWindow.document.body;if(a==null)return"";a=a.innerHTML;if(a.indexOf("<PRE>")==0||a.indexOf("<pre>")==0)a=a.substring(5,a.length-7);return a};
dwr.engine._processCometResponse=function(a,b){if(b.charsProcessed!=a.length)if(a.length==0)b.charsProcessed=0;else{var c=a.indexOf("//#DWR-START#",b.charsProcessed);if(c==-1)b.charsProcessed=a.length;else{var d=a.lastIndexOf("//#DWR-END#");if(d!=-1){b.charsProcessed=a.charCodeAt(d+11)==13&&a.charCodeAt(d+12)==10?d+13:d+11;a=a.substring(c+13,d);dwr.engine._receivedBatch=b;dwr.engine._eval(a);dwr.engine._receivedBatch=null}}}};
dwr.engine._sendData=function(a){a.map.batchId=dwr.engine._nextBatchId;dwr.engine._nextBatchId++;dwr.engine._batches[a.map.batchId]=a;dwr.engine._batchesLength++;a.completed=false;for(var b=0;b<a.preHooks.length;b++)a.preHooks[b]();a.preHooks=null;if(a.timeout&&a.timeout!=0)a.timeoutId=setTimeout(function(){dwr.engine._abortRequest(a)},a.timeout);if(a.rpcType==dwr.engine.XMLHttpRequest)if(window.XMLHttpRequest)a.req=new XMLHttpRequest;else if(window.ActiveXObject&&!(navigator.userAgent.indexOf("Mac")>=
0&&navigator.userAgent.indexOf("MSIE")>=0))a.req=dwr.engine._newActiveXObject(dwr.engine._XMLHTTP);var c;if(a.req){if(a.async)a.req.onreadystatechange=function(){typeof dwr!="undefined"&&dwr.engine._stateChange(a)};if(a.isPoll){dwr.engine._pollReq=a.req;if(!(document.all&&!window.opera))a.req.batch=a}b=navigator.userAgent.indexOf("Safari/");if(b>=0){b=navigator.userAgent.substring(b+7);if(parseInt(b,10)<400)if(dwr.engine._allowGetForSafariButMakeForgeryEasier=="true")a.httpMethod="GET";else dwr.engine._handleWarning(a,
{name:"dwr.engine.oldSafari",message:"Safari GET support disabled. See getahead.org/dwr/server/servlet and allowGetForSafariButMakeForgeryEasier."})}a.mode=a.isPoll?dwr.engine._ModePlainPoll:dwr.engine._ModePlainCall;b=dwr.engine._constructRequest(a);try{a.req.open(a.httpMethod,b.url,a.async);try{for(c in a.headers){var d=a.headers[c];typeof d=="string"&&a.req.setRequestHeader(c,d)}a.headers["Content-Type"]||a.req.setRequestHeader("Content-Type","text/plain")}catch(e){dwr.engine._handleWarning(a,
e)}a.req.send(b.body);a.async||dwr.engine._stateChange(a)}catch(f){dwr.engine._handleError(a,f)}}else if(a.rpcType!=dwr.engine.ScriptTag){d=a.isPoll?"dwr-if-poll-"+a.map.batchId:"dwr-if-"+a.map.batchId;a.div=document.createElement("div");document.body.appendChild(a.div);a.div.innerHTML="<iframe src='javascript:void(0)' frameborder='0' style='width:0px;height:0px;border:0;' id='"+d+"' name='"+d+"' onload='dwr.engine._iframeLoadingComplete ("+a.map.batchId+");'></iframe>";a.document=document;a.iframe=
a.document.getElementById(d);a.iframe.batch=a;a.mode=a.isPoll?dwr.engine._ModeHtmlPoll:dwr.engine._ModeHtmlCall;a.isPoll&&dwr.engine._outstandingIFrames.push(a.iframe);b=dwr.engine._constructRequest(a);if(a.httpMethod=="GET")a.iframe.setAttribute("src",b.url);else{a.form=a.document.createElement("form");a.form.setAttribute("id","dwr-form");a.form.setAttribute("action",b.url);a.form.setAttribute("style","display:none;");a.form.setAttribute("target",d);a.form.target=d;a.form.setAttribute("method",a.httpMethod);
for(c in a.map){d=a.map[c];if(typeof d!="function"){b=a.document.createElement("input");b.setAttribute("type","hidden");b.setAttribute("name",c);b.setAttribute("value",d);a.form.appendChild(b)}}a.document.body.appendChild(a.form);a.form.submit()}}else{a.httpMethod="GET";a.mode=a.isPoll?dwr.engine._ModePlainPoll:dwr.engine._ModePlainCall;b=dwr.engine._constructRequest(a);a.script=document.createElement("script");a.script.id="dwr-st-"+a.map["c0-id"];a.script.src=b.url;document.body.appendChild(a.script)}};
dwr.engine._ModePlainCall="/call/plaincall/";dwr.engine._ModeHtmlCall="/call/htmlcall/";dwr.engine._ModePlainPoll="/call/plainpoll/";dwr.engine._ModeHtmlPoll="/call/htmlpoll/";
dwr.engine._constructRequest=function(a){var b={url:a.path+a.mode,body:null};b.url+=a.isPoll==true?"ReverseAjax.dwr":a.map.callCount==1?a.map["c0-scriptName"]+"."+a.map["c0-methodName"]+".dwr":"Multiple."+a.map.callCount+".dwr";var c=location.href.match(/jsessionid=([^?]+)/);if(c!=null)b.url+=";jsessionid="+c[1];var d;if(a.httpMethod=="GET"){a.map.callCount=""+a.map.callCount;b.url+="?";for(d in a.map)if(typeof a.map[d]!="function")b.url+=encodeURIComponent(d)+"="+encodeURIComponent(a.map[d])+"&";
b.url=b.url.substring(0,b.url.length-1)}else{b.body="";if(document.all&&!window.opera){c=[];for(d in a.map)typeof a.map[d]!="function"&&c.push(d+"="+a.map[d]+dwr.engine._postSeperator);b.body=c.join("")}else for(d in a.map)if(typeof a.map[d]!="function")b.body+=d+"="+a.map[d]+dwr.engine._postSeperator;b.body=dwr.engine._contentRewriteHandler(b.body)}b.url=dwr.engine._urlRewriteHandler(b.url);return b};
dwr.engine._stateChange=function(a){var b;if(a.completed)dwr.engine._debug("Error: _stateChange() with batch.completed");else{var c=a.req;try{if(c.readyState!=4)return}catch(d){dwr.engine._handleWarning(a,d);dwr.engine._clearUp(a);return}if(dwr.engine._unloading)dwr.engine._debug("Ignoring reply from server as page is unloading.");else{try{var e=c.responseText;e=dwr.engine._replyRewriteHandler(e);var f=c.status;if(e==null||e=="")dwr.engine._handleWarning(a,{name:"dwr.engine.missingData",message:"No data received from server"});
else if(f!=200)dwr.engine._handleError(a,{name:"dwr.engine.http."+f,message:c.statusText});else{var h=c.getResponseHeader("Content-Type");if(!h.match(/^text\/plain/)&&!h.match(/^text\/javascript/))h.match(/^text\/html/)&&typeof a.textHtmlHandler=="function"?a.textHtmlHandler({status:f,responseText:e,contentType:h}):dwr.engine._handleWarning(a,{name:"dwr.engine.invalidMimeType",message:"Invalid content type: '"+h+"'"});else if(a.isPoll&&a.map.partialResponse==dwr.engine._partialResponseYes)dwr.engine._processCometResponse(e,
a);else if(e.search("//#DWR")==-1)dwr.engine._handleWarning(a,{name:"dwr.engine.invalidReply",message:"Invalid reply from server"});else b=e}}catch(k){dwr.engine._handleWarning(a,k)}dwr.engine._callPostHooks(a);dwr.engine._receivedBatch=a;if(b!=null)b=b.replace(dwr.engine._scriptTagProtection,"");dwr.engine._eval(b);dwr.engine._receivedBatch=null;dwr.engine._validateBatch(a);a.completed||dwr.engine._clearUp(a)}}};
dwr.engine._validateBatch=function(a){if(!a.completed)for(var b=0;b<a.map.callCount;b++)if(a.handlers[b]!=null){dwr.engine._handleWarning(a,{name:"dwr.engine.incompleteReply",message:"Incomplete reply from server"});break}};dwr.engine._iframeLoadingComplete=function(a){(a=dwr.engine._batches[a])&&dwr.engine._validateBatch(a)};
dwr.engine._remoteHandleCallback=function(a,b,c){var d=dwr.engine._batches[a];if(d==null)dwr.engine._debug("Warning: batch == null in remoteHandleCallback for batchId="+a,true);else try{var e=d.handlers[b];d.handlers[b]=null;if(e)typeof e.callback=="function"&&e.callback(c);else dwr.engine._debug("Warning: Missing handlers. callId="+b,true)}catch(f){dwr.engine._handleError(d,f)}};
dwr.engine._remoteHandleException=function(a,b,c){a=dwr.engine._batches[a];if(a==null)dwr.engine._debug("Warning: null batch in remoteHandleException",true);else{var d=a.handlers[b];a.handlers[b]=null;if(d==null)dwr.engine._debug("Warning: null handlers in remoteHandleException",true);else{if(c.message==undefined)c.message="";if(typeof d.exceptionHandler=="function")d.exceptionHandler(c.message,c);else typeof a.errorHandler=="function"&&a.errorHandler(c.message,c)}}};
dwr.engine._remoteHandleBatchException=function(a,b){var c=dwr.engine._receivedBatch==null&&b!=null;if(c)dwr.engine._receivedBatch=dwr.engine._batches[b];if(a.message==undefined)a.message="";dwr.engine._handleError(dwr.engine._receivedBatch,a);if(c){dwr.engine._receivedBatch=null;dwr.engine._clearUp(dwr.engine._batches[b])}};
dwr.engine._remotePollCometDisabled=function(a,b){dwr.engine.setActiveReverseAjax(false);var c=dwr.engine._receivedBatch==null&&b!=null;if(c)dwr.engine._receivedBatch=dwr.engine._batches[b];if(a.message==undefined)a.message="";dwr.engine._handleError(dwr.engine._receivedBatch,a);if(c){dwr.engine._receivedBatch=null;dwr.engine._clearUp(dwr.engine._batches[b])}};dwr.engine._remoteBeginIFrameResponse=function(a){if(a!=null)dwr.engine._receivedBatch=a.batch;dwr.engine._callPostHooks(dwr.engine._receivedBatch)};
dwr.engine._remoteEndIFrameResponse=function(){dwr.engine._clearUp(dwr.engine._receivedBatch);dwr.engine._receivedBatch=null};dwr.engine._eval=function(a){if(a==null)return null;if(a==""){dwr.engine._debug("Warning: blank script",true);return null}return eval(a)};dwr.engine._abortRequest=function(a){if(a&&!a.completed){dwr.engine._clearUp(a);a.req&&a.req.abort();dwr.engine._handleError(a,{name:"dwr.engine.timeout",message:"Timeout"})}};
dwr.engine._callPostHooks=function(a){if(a.postHooks){for(var b=0;b<a.postHooks.length;b++)a.postHooks[b]();a.postHooks=null}};
dwr.engine._clearUp=function(a){if(a)if(a.completed)dwr.engine._debug("Warning: Double complete",true);else{a.div&&a.div.parentNode.removeChild(a.div);if(a.iframe){for(var b=0;b<dwr.engine._outstandingIFrames.length;b++)dwr.engine._outstandingIFrames[b]==a.iframe&&dwr.engine._outstandingIFrames.splice(b,1);a.iframe.parentNode.removeChild(a.iframe)}a.form&&a.form.parentNode.removeChild(a.form);if(a.req){if(a.req==dwr.engine._pollReq)dwr.engine._pollReq=null;delete a.req}if(a.timeoutId){clearTimeout(a.timeoutId);
delete a.timeoutId}if(a.map&&(a.map.batchId||a.map.batchId==0)){delete dwr.engine._batches[a.map.batchId];dwr.engine._batchesLength--}a.completed=true;if(dwr.engine._batchQueue.length!=0){a=dwr.engine._batchQueue.shift();dwr.engine._sendData(a)}}else dwr.engine._debug("Warning: null batch in dwr.engine._clearUp()",true)};
dwr.engine._unloader=function(){dwr.engine._unloading=true;dwr.engine._batchQueue.length=0;for(var a in dwr.engine._batches){var b=dwr.engine._batches[a];if(b&&b.map){b.req&&b.req.abort();dwr.engine._clearUp(b)}}};if(window.addEventListener)window.addEventListener("unload",dwr.engine._unloader,false);else window.attachEvent&&window.attachEvent("onunload",dwr.engine._unloader);
dwr.engine._handleError=function(a,b){if(typeof b=="string")b={name:"unknown",message:b};if(b.message==null)b.message="";if(b.name==null)b.name="unknown";if(a&&typeof a.errorHandler=="function")a.errorHandler(b.message,b);else dwr.engine._errorHandler&&dwr.engine._errorHandler(b.message,b);a&&dwr.engine._clearUp(a)};
dwr.engine._handleWarning=function(a,b){if(typeof b=="string")b={name:"unknown",message:b};if(b.message==null)b.message="";if(b.name==null)b.name="unknown";if(a&&typeof a.warningHandler=="function")a.warningHandler(b.message,b);else dwr.engine._warningHandler&&dwr.engine._warningHandler(b.message,b);a&&dwr.engine._clearUp(a)};
dwr.engine._serializeAll=function(a,b,c,d){if(c==null)a.map[d]="null:null";else switch(typeof c){case "boolean":a.map[d]="boolean:"+c;break;case "number":a.map[d]="number:"+c;break;case "string":a.map[d]="string:"+encodeURIComponent(c);break;case "object":a.map[d]=c instanceof String?"String:"+encodeURIComponent(c):c instanceof Boolean?"Boolean:"+c:c instanceof Number?"Number:"+c:c instanceof Date?"Date:"+c.getTime():c&&c.join?dwr.engine._serializeArray(a,b,c,d):dwr.engine._serializeObject(a,b,c,
d);break;case "function":break;default:dwr.engine._handleWarning(null,{name:"dwr.engine.unexpectedType",message:"Unexpected type: "+typeof c+", attempting default converter."});a.map[d]="default:"+c;break}};dwr.engine._lookup=function(a,b,c){for(var d,e=0;e<a.length;e++)if(a[e].data==b){d=a[e];break}if(d)return"reference:"+d.name;a.push({data:b,name:c});return null};
dwr.engine._serializeObject=function(a,b,c,d){var e=dwr.engine._lookup(b,c,d);if(e)return e;if(c.nodeName&&c.nodeType)return dwr.engine._serializeXml(a,b,c,d);d="Object_"+dwr.engine._getObjectClassName(c)+":{";var f;for(f in c)if(typeof c[f]!="function"){a.paramCount++;e="c"+dwr.engine._batch.map.callCount+"-e"+a.paramCount;dwr.engine._serializeAll(a,b,c[f],e);d+=encodeURIComponent(f)+":reference:"+e+", "}if(d.substring(d.length-2)==", ")d=d.substring(0,d.length-2);d+="}";return d};
dwr.engine._errorClasses={Error:Error,EvalError:EvalError,RangeError:RangeError,ReferenceError:ReferenceError,SyntaxError:SyntaxError,TypeError:TypeError,URIError:URIError};
dwr.engine._getObjectClassName=function(a){if(a&&a.constructor&&a.constructor.toString){var b=a.constructor.toString();if((b=b.match(/function\s+(\w+)/))&&b.length==2)return b[1]}if(a&&a.constructor)for(var c in dwr.engine._errorClasses)if(a.constructor==dwr.engine._errorClasses[c])return c;if(a){b=Object.prototype.toString.call(a);if((b=b.match(/\[object\s+(\w+)/))&&b.length==2)return b[1]}return"Object"};
dwr.engine._serializeXml=function(a,b,c,d){if(a=dwr.engine._lookup(b,c,d))return a;c=window.XMLSerializer?(new XMLSerializer).serializeToString(c):c.toXml?c.toXml:c.innerHTML;return"XML:"+encodeURIComponent(c)};
dwr.engine._serializeArray=function(a,b,c,d){if(d=dwr.engine._lookup(b,c,d))return d;if(document.all&&!window.opera){var e=["Array:["];for(d=0;d<c.length;d++){d!=0&&e.push(",");a.paramCount++;var f="c"+dwr.engine._batch.map.callCount+"-e"+a.paramCount;dwr.engine._serializeAll(a,b,c[d],f);e.push("reference:");e.push(f)}e.push("]");e=e.join("")}else{e="Array:[";for(d=0;d<c.length;d++){if(d!=0)e+=",";a.paramCount++;f="c"+dwr.engine._batch.map.callCount+"-e"+a.paramCount;dwr.engine._serializeAll(a,b,
c[d],f);e+="reference:";e+=f}e+="]"}return e};
dwr.engine._unserializeDocument=function(a){var b;if(window.DOMParser){b=(new DOMParser).parseFromString(a,"text/xml");if(!b.documentElement||b.documentElement.tagName=="parsererror"){a=b.documentElement.firstChild.data;a+="\n"+b.documentElement.firstChild.nextSibling.firstChild.data;throw a;}return b}else if(window.ActiveXObject){b=dwr.engine._newActiveXObject(dwr.engine._DOMDocument);b.loadXML(a);return b}else{b=document.createElement("div");b.innerHTML=a;return b}};
dwr.engine._newActiveXObject=function(a){for(var b,c=0;c<a.length;c++)try{b=new ActiveXObject(a[c]);break}catch(d){}return b};dwr.engine._debug=function(a,b){var c=false;try{if(window.console){b&&window.console.trace&&window.console.trace();window.console.log(a);c=true}else if(window.opera&&window.opera.postError){window.opera.postError(a);c=true}}catch(d){}if(!c)if(b=document.getElementById("dwr-debug")){a=a+"<br/>"+b.innerHTML;if(a.length>2048)a=a.substring(0,2048);b.innerHTML=a}};if(dwrUser==null)var dwrUser={};dwrUser.sayHello=function(a,b){dwr.engine._execute(dwr.engine._defaultPath,"dwrUser","sayHello",a,b)};dwrUser.userList=function(a,b){dwr.engine._execute(dwr.engine._defaultPath,"dwrUser","userList",a,b)};
